### PR TITLE
Update Configuration.h

### PR DESCRIPTION
**Pull request by a4jp-com**
2 changes for now

### CODE REVIEW

**Comment by thinkyhead** [comment]
How is the endstop inversion and axis direction looking? I just left them at their defaults.

**Comment by a4jp-com** [comment]
I sent my printer off to get the z-axis rod fixed and should get it back around the 24th. I can check after then. Thank you so much for your help ^^

**Comment by thinkyhead** [comment]
I hope you didn't have to send it very far! Keep me posted when you have the machine back. I know we're getting pretty close to making it work....

**Comment by a4jp-com** [comment]
I should get it back by about the 24th ^^

**Pull request merged**
